x-base-app-conf: &base_app_conf
  env_file: .env
  stdin_open: true
  tty: true
  restart: always

services:
  django_app:
    <<: *base_app_conf
    image: django_app:latest
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./app:/src/app"
    depends_on:
      - db
      - django-migrations
      - huey
      - redis # Dodaj Redis jako zależność

  django-migrations:
    <<: *base_app_conf
    image: django_app:latest
    container_name: django-migrations
    command: python manage.py migrate
    restart: no
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - "./app:/src/app"
    depends_on:
      - db

  huey:
    <<: *base_app_conf
    image: django_app:latest
    container_name: huey
    command: python manage.py run_huey
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - "./app:/src/app"
    depends_on:
      - db
      - redis # Redis jako zależność dla Huey

  db:
    image: postgres:17.0-alpine
    container_name: db
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - django_app_db:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  django_app_db:
  elasticsearch_data:
