# Generated by Django 4.2.7 on 2024-10-23 19:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0004_event_lecturers_roomequipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
