# Generated by Django 4.2.7 on 2024-11-24 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0009_alter_meeting_meeting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.CharField(max_length=100)),
                ('description_pl', models.TextField()),
                ('description_en', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_equipment',
        ),
        migrations.DeleteModel(
            name='RoomEquipment',
        ),
        migrations.AddField(
            model_name='roomattribute',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='room_reserve.room'),
        ),
    ]
