# Generated by Django 4.2.7 on 2024-12-07 17:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0015_meeting_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=colorfield.fields.ColorField(default='#2873FF', image_field=None, max_length=25, samples=None),
        ),
    ]
