# Generated by Django 4.2.7 on 2024-12-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0017_event_is_approved_event_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin'), ('Lecturer', 'Lecturer'), ('Guest', 'Guest')], default=0, max_length=50, verbose_name='User Type'),
            preserve_default=False,
        ),
    ]
