# Generated by Django 4.2.7 on 2024-12-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0018_notification'),
        ('room_reserve', '0019_user_department_alter_user_first_name_and_more'),
    ]

    operations = [
    ]
