# Generated by Django 4.2.7 on 2024-12-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0019_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin'), ('Lecturer', 'Lecturer'), ('Guest', 'Guest')], default='Student', max_length=50, verbose_name='User Type'),
        ),
    ]
