# Generated by Django 4.2.7 on 2024-12-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0020_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Admin', 'Admin'), ('Lecturer', 'Lecturer'), ('Guest', 'Guest')], help_text='Typ użytkownika, jeśli powiadomienie jest wysyłane do grupy', max_length=50, null=True),
        ),
    ]
