# Generated by Django 4.2.7 on 2024-12-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0020_merge_20241214_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
