# Generated by Django 4.2.7 on 2024-12-16 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0021_notification_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('group_type', models.CharField(choices=[('academic_year', 'Grupa rocznikowa'), ('lecturer_group', 'Grupa wykładowcy'), ('personal_group', 'Grupa osobista')], default='personal_group', max_length=50, verbose_name='group type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_groups', to=settings.AUTH_USER_MODEL, verbose_name='group admin')),
                ('meetings', models.ManyToManyField(blank=True, related_name='assigned_groups', to='room_reserve.meeting', verbose_name='assigned meetings')),
                ('members', models.ManyToManyField(blank=True, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='group members')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
