# Generated by Django 4.2.7 on 2024-12-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0020_status_note'),
        ('room_reserve', '0023_alter_notification_user'),
    ]

    operations = [
    ]
