# Generated by Django 4.2.7 on 2024-12-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0025_event_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
