# Generated by Django 4.2.7 on 2024-12-18 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0026_note_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_groups', to=settings.AUTH_USER_MODEL, verbose_name='group admins'),
        ),
    ]
