# Generated by Django 4.2.7 on 2024-12-18 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0027_remove_group_admin_group_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
