# Generated by Django 4.2.7 on 2024-12-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0025_remove_user_department'),
        ('room_reserve', '0027_remove_group_admin_group_admins'),
    ]

    operations = [
    ]
