# Generated by Django 4.2.7 on 2024-12-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0028_merge_20241218_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='event_logos/', verbose_name='Event Logo'),
        ),
    ]
