# Generated by Django 4.2.7 on 2024-12-19 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0028_group_invite_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='invite_token',
        ),
        migrations.AddField(
            model_name='group',
            name='invite_link',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
