# Generated by Django 4.2.7 on 2024-12-19 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0029_remove_group_invite_token_group_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='join_requests', to=settings.AUTH_USER_MODEL, verbose_name='Join Requests'),
        ),
    ]
