# Generated by Django 4.2.7 on 2024-12-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0029_event_logo'),
        ('room_reserve', '0030_group_join_requests'),
    ]

    operations = [
    ]
