# Generated by Django 4.2.7 on 2024-12-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0031_merge_0029_event_logo_0030_group_join_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='assigned_groups', to='room_reserve.event', verbose_name='assigned events'),
        ),
    ]
