# Generated by Django 4.2.7 on 2024-12-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0036_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Admin', 'Admin'), ('Lecturer', 'Lecturer'), ('Guest', 'Guest'), ('Organizer', 'Organizer')], help_text='Typ użytkownika, jeśli powiadomienie jest wysyłane do grupy', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin'), ('Lecturer', 'Lecturer'), ('Guest', 'Guest'), ('Organizer', 'Organizer')], default='Guest', max_length=50, verbose_name='User Type'),
        ),
    ]
