# Generated by Django 4.2.7 on 2025-01-03 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0038_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='lecturers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type__in': ['Lecturer', 'Organizer']}, related_name='lecturer_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organizers/Lecturers'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
    ]
