# Generated by Django 4.2.7 on 2025-01-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0038_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_api',
            field=models.BooleanField(default=False, verbose_name='is api'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_excel',
            field=models.BooleanField(default=False, verbose_name='is excel'),
        ),
    ]
