# Generated by Django 4.2.7 on 2025-01-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0040_roomplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomplan',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='roomplan',
            name='y_position',
        ),
        migrations.AddField(
            model_name='roomplan',
            name='svg_shapes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='building_plans/'),
        ),
    ]
