# Generated by Django 4.2.7 on 2025-01-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0040_remove_event_organizer_event_organizer'),
        ('room_reserve', '0042_rename_svg_shapes_roomplan_svg_points'),
    ]

    operations = [
    ]
