# Generated by Django 4.2.7 on 2025-01-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0043_merge_20250105_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
