# Generated by Django 4.2.7 on 2025-01-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0044_remove_user_is_staff_remove_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_dashboard', 'Can view dashboard')]},
        ),
    ]
