# Generated by Django 4.2.7 on 2025-01-07 19:55

from django.db import migrations, models
from django.db.models import Q


def update_users_permissions(apps, schema_editor):
    User = apps.get_model("room_reserve", "User")

    User.objects.filter(Q(is_superuser=True) | Q(is_staff=True)).update(
        user_type="Admin",
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("room_reserve", "0044_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email address"),
        ),
        migrations.RunPython(update_users_permissions, reverse_func),
    ]
