# Generated by Django 4.2.7 on 2025-01-07 20:20

from django.db import migrations
import room_reserve.models.auth


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0045_alter_user_emailll'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', room_reserve.models.auth.DefaultUserManager()),
            ],
        ),
    ]
